# Generated by Django 2.1.5 on 2021-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0003_auto_20210324_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=225),
        ),
    ]
