# Generated by Django 2.1.5 on 2021-05-29 09:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0006_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
