# Generated by Django 3.2.4 on 2021-07-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0007_auto_20210529_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
