# Generated by Django 3.2.4 on 2021-07-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0009_auto_20210716_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link to read the article', max_length=225),
        ),
    ]
